---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.consdata.com
spec:
  scope: Namespaced
  group: consdata.com
  names:
    kind: VaultSecret
    singular: vaultsecret
    plural: vaultsecrets
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Name of the secret"
                path:
                  type: string
                  description: "Secret path in vault"
                vault:
                  type: string
                  description: "Vault addr"
                role:
                  type: string
                  description: "Vault role"
                type:
                  type: string
                  description: "Secret type"

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-auth
  namespace: default


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vaultsecrets-operator-role
rules:
  - apiGroups :
      - consdata.com
    resources:
      - vaultsecrets
    verbs: [ get, list, watch, patch, create, update, delete ]
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: [ patch, get, list, create, update, delete, watch ]
  - apiGroups: [ kopf.dev ]
    resources: [ clusterkopfpeerings ]
    verbs: [ list, watch, patch, get ]
  - apiGroups: [ apiextensions.k8s.io ]
    resources: [ customresourcedefinitions ]
    verbs: [ list, watch ]
  - apiGroups: [ "" ]
    resources: [ namespaces ]
    verbs: [ list, watch ]
  - apiGroups: [ admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1 ]
    resources: [ validatingwebhookconfigurations, mutatingwebhookconfigurations ]
    verbs: [ create, patch ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: kopf-role-namespaced
rules:
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [kopf.dev]
    resources: [kopfexamples]
    verbs: [list, watch, patch]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: kopf-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kopf-role-namespaced
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultsecrets-operator-role
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  namespace: default
  labels:
    app: vault-secrets-operator
spec:
  selector:
    matchLabels:
      app: vault-secrets-operator
  template:
    metadata:
      labels:
        app: vault-secrets-operator
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: vault-secrets-operator
          image: consdata/vault-secrets-operator:latest

