
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - consdata.com.consdata.com
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consdata.com.consdata.com
  resources:
  - vaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - consdata.com.consdata.com
  resources:
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
